import { PayslipTemplate } from '../types/payslip';

export const DEFAULT_TEMPLATES: PayslipTemplate[] = [
  {
    id: 'tpl_standard',
    name: 'Standard Corporate',
    description: 'Professional classic corporate layout suitable for mid-to-large businesses.',
    pageSize: 'a4',
    orientation: 'portrait',
    primaryColor: '#2563eb', // Indigo / Blue 600
    secondaryColor: '#f8fafc',
    accentColor: '#1e293b',
    fontFamily: 'Inter',
    fontSize: 'sm',
    borderStyle: 'solid',
    showCompanyLogo: true,
    showEmployeePhoto: true,
    showQrCode: true,
    showStamps: true,
    showSignatures: true,
    showYtd: true,
    showEmployerContrib: true,
    showAttendance: true,
    sectionOrder: [
      'header',
      'company_info',
      'employee_info',
      'attendance_summary',
      'earnings_deductions_table',
      'net_salary_callout',
      'ytd_summary',
      'employer_contributions',
      'payment_details',
      'signatures_stamps',
      'qr_verification',
      'notes_footer',
    ],
    customHeaderText: 'CONFIDENTIAL PAYROLL STATEMENT',
    customFooterText: 'This is a computer-generated payslip. No manual signature required if verified online.',
    isDefault: true,
  },
  {
    id: 'tpl_minimalist',
    name: 'Minimalist Modern',
    description: 'Clean, spacious, modern tech-startup style layout with sleek typography.',
    pageSize: 'a4',
    orientation: 'portrait',
    primaryColor: '#0d9488', // Teal 600
    secondaryColor: '#f1f5f9',
    accentColor: '#475569',
    fontFamily: 'Outfit',
    fontSize: 'sm',
    borderStyle: 'none',
    showCompanyLogo: true,
    showEmployeePhoto: false,
    showQrCode: true,
    showStamps: false,
    showSignatures: true,
    showYtd: false,
    showEmployerContrib: false,
    showAttendance: true,
    sectionOrder: [
      'header',
      'company_info',
      'employee_info',
      'earnings_deductions_table',
      'net_salary_callout',
      'payment_details',
      'signatures_stamps',
      'qr_verification',
    ],
    customHeaderText: 'PAYSLIP STATEMENT',
    customFooterText: 'Thank you for your valuable contribution to our team.',
  },
  {
    id: 'tpl_executive',
    name: 'Executive Detailed',
    description: 'Comprehensive report format with complete YTD, Tax calculations & Employer contributions.',
    pageSize: 'a4',
    orientation: 'portrait',
    primaryColor: '#4f46e5', // Indigo 600
    secondaryColor: '#e0e7ff',
    accentColor: '#312e81',
    fontFamily: 'Roboto',
    fontSize: 'xs',
    borderStyle: 'solid',
    showCompanyLogo: true,
    showEmployeePhoto: true,
    showQrCode: true,
    showStamps: true,
    showSignatures: true,
    showYtd: true,
    showEmployerContrib: true,
    showAttendance: true,
    sectionOrder: [
      'header',
      'company_info',
      'employee_info',
      'attendance_summary',
      'earnings_deductions_table',
      'net_salary_callout',
      'ytd_summary',
      'employer_contributions',
      'payment_details',
      'signatures_stamps',
      'qr_verification',
      'notes_footer',
    ],
    customHeaderText: 'EXECUTIVE COMPENSATION & PAYROLL SLIP',
    customFooterText: 'Official Financial Record - Strictly Confidential.',
  },
  {
    id: 'tpl_contractor',
    name: 'Contractor & Freelancer',
    description: 'Optimized layout for hourly, daily, and project-based contract employees.',
    pageSize: 'letter',
    orientation: 'portrait',
    primaryColor: '#059669', // Emerald 600
    secondaryColor: '#ecfdf5',
    accentColor: '#064e3b',
    fontFamily: 'Courier Prime',
    fontSize: 'sm',
    borderStyle: 'dashed',
    showCompanyLogo: true,
    showEmployeePhoto: false,
    showQrCode: true,
    showStamps: false,
    showSignatures: true,
    showYtd: false,
    showEmployerContrib: false,
    showAttendance: true,
    sectionOrder: [
      'header',
      'company_info',
      'employee_info',
      'attendance_summary',
      'earnings_deductions_table',
      'net_salary_callout',
      'payment_details',
      'signatures_stamps',
      'qr_verification',
    ],
    customHeaderText: 'CONTRACTOR REMUNERATION INVOICE / SLIP',
    customFooterText: 'Payment processed per independent contractor agreement.',
  },
];
